apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nvidia-build-drivers
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nvidia-build-drivers
    app.kubernetes.io/part-of: nvidia-build-drivers
  name: nvidia-build-drivers
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: nvidia-build-drivers
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: nvidia-build-drivers
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ebelarte-tenant/nvidia-build-drivers/nvidia-build-drivers@sha256:9b2bb54ee76d7dbecd907d63f5a7ef73e0d9fb76f36939007b3a01843d8d4f9a
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
