apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nvidia-build-drivers
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nvidia-build-drivers
    app.kubernetes.io/part-of: nvidia-build-drivers
  name: nvidia-build-drivers
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: nvidia-build-drivers
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: nvidia-build-drivers
    spec:
      containers:
      - image: quay.io/ebelarte/nvidia-build-drivers@sha256:619ed366770104fd5e3c23ba43c75f59d85f23151cc95488de4589eadbaf7039
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
